# Generated by Django 4.1.3 on 2023-01-04 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankingapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={},
        ),
        migrations.RemoveField(
            model_name='branch',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='district',
            name='slug',
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='register',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bankingapp.branch'),
        ),
        migrations.AlterField(
            model_name='register',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bankingapp.district'),
        ),
    ]
