# Generated by Django 4.1.3 on 2023-01-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankingapp', '0002_alter_branch_options_alter_district_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='register',
            name='gender',
            field=models.BooleanField(),
        ),
    ]
