# Generated by Django 4.1.3 on 2023-01-12 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankingapp', '0007_register_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='material',
        ),
    ]
