# Generated by Django 4.1.3 on 2023-01-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankingapp', '0008_remove_register_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='material',
            field=models.CharField(blank=True, choices=[('D', 'Debit Card'), ('C', 'Credit Card'), ('CQ', 'Cheque Book')], max_length=128),
        ),
    ]
