# Generated by Django 4.1.3 on 2023-01-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankingapp', '0010_alter_register_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='material',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
