# Generated by Django 4.1.3 on 2023-01-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankingapp', '0011_alter_register_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
