# Generated by Django 4.1.3 on 2023-01-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankingapp', '0013_alter_register_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
