# Generated by Django 4.1.3 on 2023-01-22 11:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankingapp', '0017_rename_material_register_material_choices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='birthdate',
            field=models.DateField(default=datetime.datetime.now, null=True),
        ),
    ]
