# Generated by Django 4.1.3 on 2023-03-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankingapp', '0018_register_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='age',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
